name: example
description: A project that showcases usage of swagger_parser
publish_to: 'none'
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  retrofit: ^3.0.0

dev_dependencies:
  build_runner: ^2.2.1
  carapacik_lints: ^1.2.2
  freezed: ^2.1.1
  json_serializable: ^6.4.0
  retrofit_generator: ^4.1.0
  swagger_parser: ^0.1.0

flutter:
  uses-material-design: true

swagger_parser:
  json_path: assets/swagger.json
  output_directory: lib/api
  freezed: true
