name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./swagger_parser
    strategy:
      matrix:
        sdk:
          - 2.17.7
          - 2.18.4
          - stable
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: "${{ matrix.sdk }}"
      - name: Install dependencies
        run: dart pub get
      - name: Analyze
        run: dart analyze
      - name: Run tests
        run: dart run test
